VoteApp/VoteApp/Controllers/ContestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoteApp.Models;

namespace VoteApp.Controllers
{
    public class ContestController : Controller
    {
        AppDb db = AppDb.Create();

        // GET: Contest
        public ActionResult Index()
        {
            var contest = db.Contests.FirstOrDefault();
            if (contest == null)
            {
                contest = new Contest()
                {
                    Id = Guid.NewGuid().ToString(),
                    StartDate = DateTime.Now,
                    EndDate = DateTime.Now + TimeSpan.FromDays(30)
                };
                db.Contests.Add(contest);
                db.SaveChanges();
            }
            return View(contest);
        }

        [HttpPost]
        public ActionResult Index(Contest newContest)
        {
            var contest = db.Contests.SingleOrDefault(s => s.Id == newContest.Id);
            if (contest != null)
            {
                contest.Id = newContest.Id;
                contest.StartDate = newContest.StartDate;
                contest.EndDate = newContest.EndDate;
                db.Entry(contest).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                newContest.Id = Guid.NewGuid().ToString();
                db.Contests.Add(newContest);
            }
            db.SaveChanges();
            return View(contest);
        }
    }
}

VoteApp/VoteApp/Controllers/RankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VoteApp.Models;

namespace VoteApp.Controllers
{
    public class RankController : Controller
    {
        AppDb db = AppDb.Create();

        [Route("kết-quả")]
        public ActionResult Index()
        {
            RankViewModal model = new RankViewModal();
            model.Contestants = new Dictionary<int, List<Contestant>>();
            model.Voter = new Dictionary<int, Vote>();

            var groups = db.Contestants.GroupBy(s => s.Group);
            List<Contestant> hightestVote = new List<Contestant>();
            foreach (var group in groups)
            {
                List<Contestant> contestants = group.OrderByDescending(s => s.VotedCount).ToList();
                model.Contestants.Add(group.Key, contestants);
                hightestVote.Add(contestants[0]);
            }
            foreach (var c in hightestVote)
            {
                if (c.VotedCount > 0)
                {
                    int min = c.Votes.Min(s => Math.Abs(s.VotedCount - c.VotedCount));
                    var user = c.Votes.Where(s => Math.Abs(s.VotedCount - c.VotedCount) == min).OrderBy(s => s.Time).ElementAt(0);
                    model.Voter.Add(c.Group, user);
                }
            }
            return View(model);
        }
    }
}

VoteApp/VoteApp/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VoteApp.Controllers
{
    public class StatisticsController : Controller
    {
        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }
    }
}

VoteApp/VoteApp/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using VoteApp.Models;

namespace VoteApp.Controllers
{
    public class VoteController : Controller
    {
        AppDb db = new AppDb();

        [Route("thí-sinh/{page?}")]
        public ActionResult Index(int page = 1)
        {
            Dictionary<int, string> likegroup = new Dictionary<int, string>();

            if (Request.IsAuthenticated)
            {
                var user = db.Users.Single(s => s.UserName == User.Identity.Name);
                foreach (var vote in user.Votes)
                    likegroup.Add(vote.VotedContestant.Group, vote.VotedContestant.Id);
            }
            ViewBag.LikedGroups = likegroup;
            int minute = DateTime.Now.Second; //  1-> 606 0/ mot phut thay doi  
            float percent = 1 / 10.0f * minute; //
            if (percent >= 1)
                percent -= 1;
            var data = db.Contestants.ToList();
            int offset = (int)(data.Count * percent); //tat insert giup e
            var newdata = data.Skip(offset).ToList();
            newdata.AddRange(data.Take(offset)); //cho e 5p
            PagedList<Contestant> model = new PagedList<Contestant>(newdata, page, 10);
            return View(model);
        }

     
        [Route("thí-sinh/chi-tiết/{id?}")]
        public ActionResult Detail(string id)
        {
            VoteDetailViewModel model = new VoteDetailViewModel();

            model.Contestant = db.Contestants.SingleOrDefault(s => s.Id == id || s.MS.ToLower() == id.ToLower());
            if (model.Contestant == null)
                return RedirectToAction("Index");

            var days = model.Contestant.Votes.GroupBy(s => s.Time.ToShortDateString()).ToList();
            model.LikePerDay = new Dictionary<string, int>();
            foreach (var day in days)
                model.LikePerDay.Add(day.Key, day.Count());
            model.LikedGroups = new Dictionary<int, string>();
            if (Request.IsAuthenticated)
            {
                var votes = db.Users.Single(s => s.UserName == User.Identity.Name).Votes;
                foreach (var vote in votes)
                    model.LikedGroups.Add(vote.VotedContestant.Group, vote.VotedContestant.Id);
            }

            return View(model);
        }

        [Authorize]
        [Route("bình-chọn/{id}/{count?}")]
        public async Task<JsonResult> Submit(string id, int count = 0)
        {
            Contest contest = db.Contests.FirstOrDefault();
            if (contest == null || DateTime.Now < contest.StartDate || DateTime.Now > contest.EndDate)
                return Json(new { error = "Không trong thời gian bình chọn" }, JsonRequestBehavior.AllowGet);

            Contestant contestant = db.Contestants.SingleOrDefault(s => s.Id == id);
            if (contestant == null)
                return Json(new { error = "Không tìm thấy ảnh này" }, JsonRequestBehavior.AllowGet);
            var user = db.Users.Single(s => s.UserName == User.Identity.Name);
            if (user.PasswordHash != null && user.EmailConfirmed == false)
                return Json(new { error = "Tài khoản email chưa xác thực. Bạn phải vào tài khoản email đã đăng ký để xác thực." }, JsonRequestBehavior.AllowGet);
            bool like = false;

            var vote = contestant.Votes.SingleOrDefault(s => s.VotedUser.UserName == user.UserName);
            if (vote != null)
            {
                db.Votes.Remove(vote);
                contestant.VotedCount--;
            }
            else
            {
                if (user.Votes.Any(s => s.VotedContestant.Group == contestant.Group))
                    return Json(new { error = "Bạn đã bình chọn cho một thí sinh khác cùng bản này" }, JsonRequestBehavior.AllowGet);

                contestant.Votes.Add(new Vote()
                {
                    Id = Guid.NewGuid().ToString(),
                    Time = DateTime.Now,
                    VotedCount = count,
                    VotedUser = user
                });
                like = true;
                contestant.VotedCount++;
            }

            db.Entry(contestant).State = System.Data.Entity.EntityState.Modified;
            await db.SaveChangesAsync();
            return Json(new { l = like, c = contestant.VotedCount }, JsonRequestBehavior.AllowGet);
        }

        [Route("xem/{id?}")]
        public async Task<JsonResult> ViewImg(string id)
        {
            Img c = await db.Imgs.FindAsync(id);
            if (c == null)
                return Json(new { error = "Không tìm thấy ảnh này" }, JsonRequestBehavior.AllowGet);
            DateTime? last = Session[id] as DateTime?;
            if (last == null || DateTime.Now - last > TimeSpan.FromHours(8))
            {
                Session.Add(id, DateTime.Now);
                c.Contestant.ViewedCount++;
                db.Entry(c.Contestant).State = System.Data.Entity.EntityState.Modified;
                await db.SaveChangesAsync();
            }
            return Json(null, JsonRequestBehavior.AllowGet);
        }
    }
}

VoteApp/VoteApp/Views/Shared/_AdminLeftMenuPartial.cshtml
<div class="col-md-3">
    <a class="btn btn-primary btn-block" href="@Url.Action("Index", "Contest")"><i class="glyphicon glyphicon-wrench"></i> Quản lý cuộc thi</a>
    <a class="btn btn-primary btn-block" href="@Url.Action("Index", "Departments")"><i class="glyphicon glyphicon-list"></i> Quản lý đơn vị</a>
    <a class="btn btn-primary btn-block" href="@Url.Action("Index", "Contestants")"><i class="glyphicon glyphicon-education"></i> Quản lý thí sinh</a>
    <a class="btn btn-primary btn-block" href="@Url.Action("Management", "Account")"><i class="glyphicon glyphicon-user"></i> Quản lý tài khoản</a>
    <a class="btn btn-primary btn-block" href="@Url.Action("Index", "Notifications")"><i class="glyphicon glyphicon-bell"></i> Thông báo</a>
    <a class="btn btn-primary btn-block" href="@Url.Action("Index", "Statistics")"><i class="glyphicon glyphicon-stats"></i> Thống kê</a>

</div>

VoteApp/VoteApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Vote</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @RenderSection("topmost", false)
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trang chủ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="font-weight:bold; font-size:large">
                    <li>@Html.ActionLink("Bình chọn", "Index", "Vote")</li>
                    <li>@Html.ActionLink("Xếp hạng", "Index", "Rank")</li>
                    <li>@Html.ActionLink("Liên hệ", "Contact", "Home")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <marquee direction="right">

        <H5 style="color:red">THÔNG BÁO: THỜI GIAN BÌNH CHỌN SẼ KÉO DÀI ĐẾN HẾT 16:00 NGÀY 1/12/2015</H5>

    </marquee>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="color:black">

            Copy right &copy; @DateTime.Now.Year - Charming HCMUTE 2015

            <div class="pull-right" style="padding-right: 20px;">
                Online
                <script id="_wau4zg">
                    var _wau = _wau || []; _wau.push(["classic", "2a2y9klcsp3j", "4zg"]);
                    (function () {
                        var s = document.createElement("script"); s.async = true;
                        s.src = "http://widgets.amung.us/classic.js";
                        document.getElementsByTagName("head")[0].appendChild(s);
                    })();</script>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>