VoteApp/VoteApp/Models/ContestantViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace VoteApp.Models
{
    public class ContestantViewModel
    {
        [Required]
        public string MS { get; set; }

        [Required]
        public string Name { get; set; }

        [Range(3, 99)]
        public int Age { get; set; }

        public bool Sex { get; set; }
        public bool Couple { get; set; }

        public string DepartmentId { get; set; }
    }
}

VoteApp/VoteApp/Controllers/ContestantsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using VoteApp.Models;

namespace VoteApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ContestantsController : Controller
    {
        private AppDb db = new AppDb();

        // GET: Contestants
        public async Task<ActionResult> Index()
        {
            return View(await db.Contestants.ToListAsync());
        }

        // GET: Contestants/Create
        public ActionResult Create()
        {
            ViewBag.Departments = db.Departments.ToList();
            return View();
        }

        // POST: Contestants/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ContestantViewModel model)
        {
            ViewBag.Departments = db.Departments.ToList();
            if (ModelState.IsValid)
            {
                Contestant contestant = new Contestant()
                {
                    MS = model.MS,
                    Age = model.Age,
                    Couple = model.Couple,
                    cDepartment = db.Departments.Single(s => s.Id == model.DepartmentId),
                    Name = model.Name,
                    Sex = model.Sex
                };
                if (contestant.Couple)
                    contestant.Group = 2;
                else if (contestant.Sex)
                    contestant.Group = (contestant.Age > 40 ? 1 : 0);
                else
                    contestant.Group = (contestant.Age > 30 ? 1 : 0);

                contestant.Id = Guid.NewGuid().ToString();
                contestant.ViewedCount = 0;
                contestant.VotedCount = 0;
                contestant.Imgs = new List<Img>();
                if (Request.Files.Count < 6)
                {
                    ModelState.AddModelError("", "Không thể không có hình ảnh");
                    return View(model);
                }

                for (int i = 0; i < 6; i++)
                    if (Request.Files[i].ContentLength == 0)
                    {
                        ModelState.AddModelError("", "Không thể không có hình ảnh");
                        return View(model);
                    }
                try
                {
                    for (int i = 0; i < 3; i++)
                    {
                        string ext = Request.Files[i].FileName.Substring(Request.Files[i].FileName.Length - 4, 4);
                        string fileName = Guid.NewGuid().ToString();
                        Request.Files[i].SaveAs(Server.MapPath(@"~/Content/Uploads/" + fileName + ext));
                        contestant.Imgs.Add(new Img()
                        {
                            Id = fileName,
                            FileName = (@"/Content/Uploads/" + fileName + ext)
                        });
                    }
                    for (int i = 3; i < 6; i++)
                    {
                        string ext = Request.Files[i].FileName.Substring(Request.Files[i].FileName.Length - 4, 4);
                        string fileName = Guid.NewGuid().ToString();
                        Request.Files[i].SaveAs(Server.MapPath(@"~/Content/Thumbnails/" + fileName + ext));
                        contestant.Imgs.ElementAt(i-3).cThumbnail = new Thumbnail()
                        {
                            Id = fileName,
                            FileName = (@"/Content/Thumbnails/" + fileName + ext)
                        };
                    }
                    db.Contestants.Add(contestant);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ModelState.AddModelError("", "Upload thất bại");
                    foreach (var file in contestant.Imgs)
                        if (System.IO.File.Exists(Server.MapPath(file.FileName)))
                            System.IO.File.Delete(Server.MapPath(file.FileName));
                    return View(model);
                }
            }
            return View(model);
        }

        // GET: Contestants/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contestant contestant = await db.Contestants.FindAsync(id);
            if (contestant == null)
            {
                return HttpNotFound();
            }
            return View(contestant);
        }

        // POST: Contestants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,MS,Name,Description,VotedCount,ViewdCount")] Contestant contestant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contestant).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(contestant);
        }

        // GET: Contestants/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contestant contestant = await db.Contestants.FindAsync(id);
            if (contestant == null)
            {
                return HttpNotFound();
            }
            return View(contestant);
        }

        // POST: Contestants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Contestant contestant = await db.Contestants.FindAsync(id);
            foreach (var img in contestant.Imgs)
                if (System.IO.File.Exists(Server.MapPath(img.FileName)))
                    System.IO.File.Delete(Server.MapPath(img.FileName));
            db.Contestants.Remove(contestant);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VoteApp/VoteApp/Views/Contestants/Create.cshtml
@using VoteApp.Models
@model ContestantViewModel

@{
    ViewBag.Title = "Thêm thí sinh";
}
<h4 class="page-header">Admin - Quản lí thí sinh</h4>
<div class="row" style="min-height: 420px">
    @Html.Partial("_AdminLeftMenuPartial")
    <div class="col-md-9">
        <div class="panel">
            <div class="panel-body">
                @using (Html.BeginForm("Create", "Contestants", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Thêm thí sinh</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <label class="control-label col-md-2" for="MS">Mã số</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.MS, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.MS, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Name">Họ và tên</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Description">Tuổi</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Description">Giới tính</label>
                            <div class="col-md-10">
                                <ra class="form-control">
                                    @Html.RadioButtonFor(m => m.Sex, true, new { @Id = "rdoSexTrue" })
                                    <label for="rdoSexTrue">Nam</label>
                                    @Html.RadioButtonFor(m => m.Sex, false, new { @Id = "rdoSexFalse" })
                                    <label for="rdoSexFalse">Nữ</label>
                                </ra>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Description">Nội dung thi</label>
                            <div class="col-md-10">
                                <ra class="form-control">
                                    @Html.RadioButtonFor(m => m.Couple, true, new { @Id = "rdoCoupleTrue" })
                                    <label for="rdoCoupleTrue">Thi đôi</label>
                                    @Html.RadioButtonFor(m => m.Couple, false, new { @Id = "rdoCoupleFalse" })
                                    <label for="rdoCoupleFalse">Thi đơn</label>
                                </ra>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Description">Đơn vị</label>
                            <div class="col-md-10">
                                <select class="form-control" name="DepartmentId">
                                    @{
                                        List<Department> depts = ViewBag.Departments;
                                        foreach (var dept in depts)
                                        {
                                            <option value="@dept.Id">@dept.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="control-label col-md-2">Hình ảnh</label>
                            <div class="col-md-10">
                                <input type="file" name="file" accept="image/*" />
                                <input type="file" name="file1" accept="image/*" />
                                <input type="file" name="file2" accept="image/*" />
                                <input type="file" name="file3" accept="image/*" />
                                <input type="file" name="file4" accept="image/*" />
                                <input type="file" name="file5" accept="image/*" />
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-4 pull-right">
                                <input type="submit" value="Thêm thí sinh" class="btn btn-success btn-block" />
                            </div>
                        </div>
                    </div>
                                        }
            </div>
        </div>
    </div>
</div>

VoteApp/VoteApp/Views/Contestants/Delete.cshtml
@model VoteApp.Models.Contestant

@{
    ViewBag.Title = "Xóa thí sinh";
}
<h4 class="page-header">Admin - Quản lí thí sinh</h4>
<div class="row" style="min-height: 420px">
    @Html.Partial("_AdminLeftMenuPartial")
    <div class="col-md-9">
        <div class="panel">
            <div class="panel-body">
                <h3>Bạn có chắc muốn xóa hình ảnh này?</h3>
                <hr />
                <div class="row">
                    <dl class="dl-horizontal">
                        <dt>
                            Mã số
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.MS)
                        </dd>

                        <dt>
                            Họ và tên
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Name)
                        </dd>
                    </dl>
                </div>
                @foreach (var img in Model.Imgs)
                {
                    <div class="col-md-4">
                        <img class="img-responsive thumbnail" style="max-height: 100px;max-width: 100px" src="@img.FileName" />
                    </div>
                }
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color pull-right">
                        <input type="submit" value="Xóa" class="btn btn-default" /> |
                        @Html.ActionLink("Quay lại", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
</div>

VoteApp/VoteApp/Views/Contestants/Details.cshtml
@model VoteApp.Models.Contestant

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Contestant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VotedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VotedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViewdCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViewdCount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VoteApp/VoteApp/Views/Contestants/Edit.cshtml
@model VoteApp.Models.Contestant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Contestant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.MS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VotedCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VotedCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VotedCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ViewdCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ViewdCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewdCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

VoteApp/VoteApp/Views/Contestants/Index.cshtml
@model IEnumerable<VoteApp.Models.Contestant>

@{
    ViewBag.Title = "Thêm thí sinh";
}

<h4 class="page-header">Admin - Quản lí thí sinh</h4>
<div class="row" style="min-height: 420px">
    @Html.Partial("_AdminLeftMenuPartial")
    <div class="col-md-9">
        <div class="panel">
            <div class="panel-body">
                <p>
                    @Html.ActionLink("Thêm thí sinh", "Create", null, new { @class = "btn btn-primary" })
                </p>
                <table class="table table-bordered table-hover table-responsive table-striped">
                    <tr>
                        <th>
                            Mã số
                        </th>
                        <th>
                            Họ và tên
                        </th>
                        <th>Giới tính</th>
                        <th>Độ tuổi</th>
                        <th>Đơn vị</th>
                        <th>Nội dung thi</th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
            {
                        <tr>
                            <td>
                                @item.MS
                            </td>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @(item.Sex?"Nam":"Nữ")
                            </td>
                            <td>
                                @item.Age
                            </td>
                            <td>
                                @item.cDepartment.Name
                            <td>
                                @(item.Couple ? "Thi đôi" : "Thi đơn")
                            </td>
                            <td>
                                @*@Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |*@
                                @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
                            </td>
                        </tr>
                    }

                </table>
            </div>
        </div>
    </div>
</div>