VoteApp/VoteApp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VoteApp.Controllers
{
    public class TestController : Controller
    {
        private Dictionary<string, int> data = new Dictionary<string, int>()
        {
            {"A",15 },
            {"B",16 },
            {"C",17 },
            {"D",18 },
        };

        // GET: Test
        public ActionResult Index(int fillter = 0)
        {
            ViewBag.fillter = fillter;
            return View();
        }

        public ActionResult GetData(int fillter = 0)
        {
            List<string> models = new List<string>();
            ViewBag.fillter = fillter;

            switch (fillter)
            {
                case 0:
                    foreach (var item in data)
                        models.Add(item.Key);
                    break;
                case 1:
                    foreach (var item in data)
                        if (item.Value % 2 == 0)
                            models.Add(item.Key);
                    break;
                default:
                    foreach (var item in data)
                        if (item.Value % 2 != 0)
                            models.Add(item.Key);
                    break;
            }
            return PartialView("_Data", models);
        }
    }
}

VoteApp/VoteApp/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "Test", FormMethod.Get, new { id = "fillterForm" }))
{
    <input type="hidden" id="fillter" name="fillter" value="@ViewBag.fillter" />
    <select id="fillter_option">
        <option @(ViewBag.fillter == 0 ? "checked" : "") value="0">Tac ca</option>
        <option @(ViewBag.fillter == 0 ? "checked" : "") value="1">Chan</option>
        <option @(ViewBag.fillter == 0 ? "checked" : "") value="2">Le</option>
    </select>
    <a class="btn btn-primary" onclick="submit()">Submit</a>
}
<div id="content">
    @Html.Action("GetData", new { fillter = ViewBag.fillter })
</div>
@section scripts{
    <script>
        $('#fillter_option').change(function () {
            submit();
        })
        function submit() {
            $.ajax({
                url: '@Url.Action("GetData")?fillter=' + $('#fillter_option').val()
            }).done(function (data) {
                $('#content').html(data);
            });
        }
    </script>
}

VoteApp/VoteApp/Views/Test/_Data.cshtml
@model List<string>

 <div class="panel panel-primary">
     <ul>
         @foreach (var item in Model)
         {
             <li>@item</li>
         }
     </ul>
</div>